# Generated by Django 6.0.2 on 2026-02-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_all", "0002_alter_question_test_alter_test_upload_test_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranswer",
            name="selected_option",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
