# Generated by Django 6.0.2 on 2026-02-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_all", "0003_alter_useranswer_selected_option"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usertestattempt",
            unique_together=set(),
        ),
    ]
