# Generated by Django 6.0.2 on 2026-02-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_all", "0004_alter_usertestattempt_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="test_upload",
            name="subject",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
