# Generated by Django 6.0.3 on 2026-04-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_all", "0005_test_upload_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test_upload",
            name="pdf",
        ),
        migrations.AddField(
            model_name="question",
            name="topic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="test_upload",
            name="json_file",
            field=models.FileField(blank=True, null=True, upload_to="tests/json_data/"),
        ),
    ]
