# Generated by Django 6.0.3 on 2026-04-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_all", "0006_remove_test_upload_pdf_question_topic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="test_upload",
            name="json_data",
            field=models.JSONField(
                blank=True,
                help_text="Paste JSON content directly here, or upload a JSON file above.",
                null=True,
            ),
        ),
    ]
