# Generated by Django 6.0.3 on 2026-04-04 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_mcq", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcqquestion",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="mcqsession",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="pdfdocument",
            name="uploaded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="answered_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
