# Generated by Django 6.0.3 on 2026-04-06 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_mcq", "0003_weaktopic"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcqquestion",
            name="topic",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="weaktopic",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weak_topics",
                to="pdf_mcq.mcqquestion",
            ),
        ),
    ]
