# Generated by Django 6.0.3 on 2026-04-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_mcq", "0004_mcqquestion_topic_weaktopic_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcqquestion",
            name="topic",
            field=models.CharField(
                blank=True, default="General", max_length=200, null=True
            ),
        ),
        migrations.DeleteModel(
            name="WeakTopic",
        ),
    ]
