# Generated by Django 6.0.3 on 2026-04-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_mcq", "0005_alter_mcqquestion_topic_delete_weaktopic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcqquestion",
            name="topic",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
