# Generated by Django 6.0.1 on 2026-04-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_mcq", "0006_alter_mcqquestion_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcqquestion",
            name="topic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
