# Generated by Django 6.0.1 on 2026-04-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_mcq", "0007_alter_mcqquestion_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcqsession",
            name="time_taken",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
