# Generated by Django 6.0.3 on 2026-04-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_mcq", "0009_feedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="created_at",
            new_name="submitted_at",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="message",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="subject",
        ),
        migrations.AddField(
            model_name="feedback",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="quality_rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1 - Very Poor"),
                    (2, "2 - Poor"),
                    (3, "3 - Average"),
                    (4, "4 - Good"),
                    (5, "5 - Excellent"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="relevance_rating",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No")],
                max_length=3,
                null=True,
            ),
        ),
    ]
