# Generated by Django 6.0.3 on 2026-05-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_mcq", "0010_rename_created_at_feedback_submitted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcqsession",
            name="pdfs",
            field=models.ManyToManyField(
                related_name="mcq_sessions", to="pdf_mcq.pdfdocument"
            ),
        ),
    ]
