# Generated by Django 6.0.3 on 2026-05-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_mcq", "0011_mcqsession_pdfs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcqsession",
            name="pdfs",
            field=models.ManyToManyField(
                related_name="mcq_sessions_with_pdf", to="pdf_mcq.pdfdocument"
            ),
        ),
    ]
