# Generated by Django 6.0.3 on 2026-04-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_mcq", "0011_mcqsession_faiss_index_path_mcqsession_pdf_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfdocument",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="user_pdfs/"),
        ),
    ]
