# Generated by Django 6.0.3 on 2026-05-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_mcq", "0012_alter_mcqsession_pdfs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mcqsession",
            name="pdfs",
        ),
        migrations.AddField(
            model_name="pdfdocument",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="user_pdfs/"),
        ),
    ]
