# Generated by Django 6.0.3 on 2026-05-02 11:49

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_mcq", "0013_remove_mcqsession_pdfs_pdfdocument_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdfdocument",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="user_pdfs/",
            ),
        ),
    ]
